#!/usr/bin/env bash
# build_missing_sifs.sh — Build all missing ARM64 SIF images
# Auto-generated by OmniBioAI studio
set -euo pipefail

SIF_DIR=/home/manish/Desktop/machine/omnibioai-tool-images/sif
DF_DIR=/home/manish/Desktop/machine/omnibioai-tool-images/dockerfiles
LOG_DIR=/home/manish/Desktop/machine/omnibioai-tool-images/build_logs
mkdir -p "$LOG_DIR"

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'

TOTAL=337
BUILT=0; FAILED=0; SKIPPED=0

build_tool() {
  local name=$1 idx=$2
  local sif="${SIF_DIR}/${name}_arm64.sif"
  local log="${LOG_DIR}/${name}.log"
  local df="${DF_DIR}/Dockerfile.${name}"

  if [ -f "$sif" ]; then
    echo -e "${YELLOW}SKIP${NC}  [$idx/$TOTAL] ${name} (SIF exists)"
    ((SKIPPED++)) || true; return 0
  fi
  if [ ! -f "$df" ]; then
    echo -e "${RED}MISS${NC}  [$idx/$TOTAL] ${name} (no Dockerfile)"
    ((FAILED++)) || true; return 1
  fi

  local tag="${name,,}"   # Docker requires lowercase image names
  echo -e "${YELLOW}BUILD${NC} [$idx/$TOTAL] ${name}..."
  if docker build --platform linux/arm64 -t "${tag}:latest" -f "$df" . >> "$log" 2>&1; then
    if singularity build "$sif" "docker-daemon://${tag}:latest" >> "$log" 2>&1; then
      echo -e "${GREEN}OK${NC}    [$idx/$TOTAL] ${name}"
      ((BUILT++)) || true
    else
      echo -e "${RED}FAIL${NC}  [$idx/$TOTAL] ${name} (singularity build failed)"
      ((FAILED++)) || true
    fi
  else
    echo -e "${RED}FAIL${NC}  [$idx/$TOTAL] ${name} (docker build failed — see $log)"
    ((FAILED++)) || true
  fi
}

echo "=== OmniBioAI SIF builder — $(date) ==="
echo "Building 329 missing SIFs in priority order"
echo

# ── Tier 0: Fast tools (< 10 min each) ───────────────────────────────────
echo -e "\n${YELLOW}--- Tier 0: Fast tools ---${NC}"
echo -e "\n${YELLOW}--- Tier 0: Fast (< 10 min) ---${NC}"
build_tool agat_convert 1
build_tool bbtools 2
build_tool bedops_merge 3
build_tool bedtools_coverage 4
build_tool bismark_align_adv 5
build_tool bowtie2_index 6
build_tool bwa_mem_adv 7
build_tool chopper 8
build_tool coverm_coverage 9
build_tool cutadapt 10
build_tool falco 11
build_tool fastani 12
build_tool fastp 13
build_tool featurecounts_adv 14
build_tool freebayes_call 15
build_tool goleft 16
build_tool kallisto_quant_adv 17
build_tool mafft_align 18
build_tool mapdamage 19
build_tool mash_sketch 20
build_tool miniasm_assembly 21
build_tool mosdepth 22
build_tool nanoplot 23
build_tool nanoq 24
build_tool plink_gwas_adv 25
build_tool plink_ld_prune 26
build_tool prodigal_annotation 27
build_tool rsem_quant 28
build_tool salmon_quant_adv 29
build_tool sambamba 30
build_tool seqkit 31
build_tool seqtk_subsample 32
build_tool skani_compare 33
build_tool star_coverage 34
build_tool star_index_build 35
build_tool strelka2_somatic 36
build_tool stringtie_adv 37
build_tool svaba 38
build_tool svaba_sv_adv 39
build_tool tabix_index 40
build_tool trimgalore 41
build_tool vcftools_stats 42

echo -e "\n${YELLOW}--- Tier 1: Medium (10-30 min) ---${NC}"
build_tool aldex2 43
build_tool ancom 44
build_tool ancombc 45
build_tool anota2seq 46
build_tool bambu_assembly 47
build_tool bbknn_integration 48
build_tool celltypist 49
build_tool changeo 50
build_tool chipseeker 51
build_tool concoct 52
build_tool consensus_cluster 53
build_tool corncob 54
build_tool crispresso2_analysis 55
build_tool crispresso2 56
build_tool customprodb 57
build_tool deconstructsigs 58
build_tool deeptools_bamcompare 59
build_tool deeptools_bamcoverage_adv 60
build_tool deseq2_de 61
build_tool dexseq_exon 62
build_tool drep 63
build_tool edger_de 64
build_tool feelnc 65
build_tool gnomix_ancestry 66
build_tool graphbin_refine 67
build_tool gtdbtk 68
build_tool hapcon_aDNA 69
build_tool harmony_integration_adv 70
build_tool htseq_count 71
build_tool humann3_pathway 72
build_tool immunarch 73
build_tool isoquant_quant 74
build_tool ldsc_heritability 75
build_tool leafcutter 76
build_tool limma_voom_de 77
build_tool linda 78
build_tool maaslin2 79
build_tool mageck 80
build_tool mageck_count_adv 81
build_tool mbimpute 82
build_tool mcscan_synteny 83
build_tool moff 84
build_tool moscot 85
build_tool muon 86
build_tool mutationalpatterns 87
build_tool nanocount_quant 88
build_tool ngstools_adna 89
build_tool orthofinder_orthologs 90
build_tool pangolin 91
build_tool panphlan_pan 92
build_tool phyloseq 93
build_tool picrust2 94
build_tool pmdtools 95
build_tool primedesign_pegrna 96
build_tool pycoqc_adv 97
build_tool pycoqc 98
build_tool pyscenic_grn 99
build_tool reditools2 100
build_tool revel 101
build_tool rf_classify 102
build_tool ribotish 103
build_tool scanpy_pipeline_adv 104
build_tool scvelo 105
build_tool scvelo_velocity 106
build_tool semibin_binning 107
build_tool sequenza_purity 108
build_tool shazam 109
build_tool sigprofiler 110
build_tool sleuth 111
build_tool sourmash 112
build_tool sparcc 113
build_tool spatialde 114
build_tool sprint_ppi 115
build_tool sqanti3_qc 116
build_tool squidpy 117
build_tool strainphlan_strain 118
build_tool swish 119
build_tool talon_transcriptome 120
build_tool tangram 121
build_tool tetranscripts 122
build_tool tmm_normalize 123
build_tool tracts_ancestry 124
build_tool trycycler_consensus 125
build_tool umap_reduce 126
build_tool unicycler_hybrid 127
build_tool vamb_binning 128
build_tool vegan 129
build_tool xgboost_classify 130
build_tool xtail 131
build_tool admet 132
build_tool mixcr 133
build_tool steinbock 134

echo -e "\n${YELLOW}--- Tier 2: Heavy (30-90 min) ---${NC}"
build_tool admixture_ancestry 135
build_tool alphapept 136
build_tool amber 137
build_tool angsd 138
build_tool annovar 139
build_tool arcashla 140
build_tool archr 141
build_tool arriba 142
build_tool ascat_purity 143
build_tool atac_pipeline 144
build_tool autodock_gpu 145
build_tool banksy 146
build_tool battenberg_cn 147
build_tool bayesspace 148
build_tool baysor 149
build_tool beagle5_impute 150
build_tool behive_base_editing 151
build_tool braker3_annotation 152
build_tool bsmap 153
build_tool cactus_alignment 154
build_tool cadd 155
build_tool canu_assembly 156
build_tool cas_offinder_search 157
build_tool casoffinder 158
build_tool cell2location 159
build_tool cell2location_deconv 160
build_tool cellchat 161
build_tool cellpose_segment_adv 162
build_tool cellranger_arc 163
build_tool cellranger 164
build_tool cellranger_count_adv 165
build_tool cellrank 166
build_tool checkm2 167
build_tool chord 168
build_tool chromvar 169
build_tool cibersortx 170
build_tool cicero 171
build_tool ciri2 172
build_tool clair3 173
build_tool clair3_longread 174
build_tool clipper 175
build_tool cobalt 176
build_tool controlfreec_cn 177
build_tool cooltools 178
build_tool cutrun 179
build_tool dada2 180
build_tool dastool 181
build_tool deepvariant 182
build_tool delly 183
build_tool diann 184
build_tool diffbind 185
build_tool dorado 186
build_tool dorado_basecall_adv 187
build_tool facets 188
build_tool fastqscreen 189
build_tool faststructure 190
build_tool flames 191
build_tool flare_ancestry 192
build_tool foldseek 193
build_tool fpocket 194
build_tool fragpipe 195
build_tool freesasa 196
build_tool gatk_filter 197
build_tool gatk_haplotype_caller 198
build_tool gatk_realign 199
build_tool gfatools_convert 200
build_tool giotto 201
build_tool gridss 202
build_tool grnboost2 203
build_tool gsea_preranked 204
build_tool guppy_basecall_adv 205
build_tool hdxms 206
build_tool hicpro 207
build_tool hifiasm 208
build_tool hifiasm_assembly_adv 209
build_tool hint 210
build_tool hrdetect_hrd 211
build_tool impute5 212
build_tool intervar 213
build_tool kaiju 214
build_tool lefse 215
build_tool liger 216
build_tool lumpy_sv 217
build_tool mageckvispr_screen 218
build_tool masurca 219
build_tool maxbin2_binning 220
build_tool mcmicro 221
build_tool megahit 222
build_tool meme 223
build_tool merip 224
build_tool merqury_eval 225
build_tool metabat2 226
build_tool metaboanalystr 227
build_tool metamorpheus 228
build_tool methyldackel 229
build_tool methylkit_dmp 230
build_tool milo 231
build_tool minigraph_align 232
build_tool minimap2_adv 233
build_tool mirdeep2 234
build_tool mixomics_analysis 235
build_tool mofa 236
build_tool mol_gnn 237
build_tool monocle3_trajectory_adv 238
build_tool mothur 239
build_tool msisensor2 240
build_tool msiseq 241
build_tool msmc2_demography 242
build_tool msmutect_ms 243
build_tool mutect2_somatic 244
build_tool mzmine 245
build_tool nextdenovo_assembly 246
build_tool nfcore_ampliseq 247
build_tool nfcore_atacseq 248
build_tool nfcore_chipseq 249
build_tool nfcore_hic 250
build_tool nfcore_mag 251
build_tool nfcore_methylseq 252
build_tool nfcore_rnaseq 253
build_tool nfcore_sarek 254
build_tool nfcore_scrnaseq 255
build_tool nfcore_taxprofiler 256
build_tool nfcore_viralrecon 257
build_tool nfcore_nanoseq 258
build_tool eager2 259
build_tool guppy 260
build_tool msfragger 261
build_tool xcms 262
build_tool octopus_call 263
build_tool odgi_pangenome 264
build_tool openms 265
build_tool opera_ms_assembly 266
build_tool optitype 267
build_tool pangraph_build 268
build_tool percolator 269
build_tool pggb_pangenome 270
build_tool phenix 271
build_tool polyphen2 272
build_tool price 273
build_tool progeny 274
build_tool prsice2 275
build_tool psmc_demography 276
build_tool purple 277
build_tool pvacseq 278
build_tool qiime2 279
build_tool qualimap 280
build_tool raven_assembly 281
build_tool rctd 282
build_tool relate_ancestry 283
build_tool rfmix_ancestry 284
build_tool scbridge 285
build_tool scdiffusion 286
build_tool scglue 287
build_tool schmutzi 288
build_tool sctype 289
build_tool scvi 290
build_tool seqwish_graph 291
build_tool seurat_cluster_adv 292
build_tool shapeit5 293
build_tool sirius 294
build_tool smartpca_pca 295
build_tool smoothxg_graph 296
build_tool snapatac2 297
build_tool spaceranger 298
build_tool spaceranger_count_adv 299
build_tool spades_assembly_adv 300
build_tool spotlight 301
build_tool starfusion 302
build_tool sweed 303
build_tool titan_cn 304
build_tool tmalign 305
build_tool tobias 306
build_tool totalvi 307
build_tool trinity_assembly_adv 308
build_tool trust4 309
build_tool velocyto 310
build_tool verkko 311
build_tool vg_construct 312
build_tool virsorter2 313
build_tool xenium 314
build_tool xlinkx 315

echo -e "\n${YELLOW}--- Tier 3: GPU/ML (> 90 min) ---${NC}"
build_tool alphafold2_monomer 316
build_tool alphafold2_multimer 317
build_tool alphamissense 318
build_tool boltz 319
build_tool chai1 320
build_tool colabfold 321
build_tool deepfri_predict 322
build_tool diffdock 323
build_tool equibind 324
build_tool esm3 325
build_tool genomic_fm 326
build_tool gnina 327
build_tool proteinmpnn 328
build_tool pytorch_train_adv 329
build_tool rapids_analysis 330
build_tool relion 331
build_tool rfdiffusion 332
build_tool rosettafold 333
build_tool scgpt 334
build_tool spliceai 335
build_tool tensorflow_train_adv 336
build_tool vae_train_adv 337

echo
echo "=== Build complete ==="
echo -e "  ${GREEN}Built:${NC}   $BUILT"
echo -e "  ${YELLOW}Skipped:${NC} $SKIPPED"
echo -e "  ${RED}Failed:${NC}  $FAILED"
