FROM bioconductor/bioconductor_docker:RELEASE_3_18
RUN R -e "BiocManager::install(c('DEXSeq','BiocParallel'))"
RUN pip3 install boto3 azure-storage-blob azure-identity --break-system-packages
COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip3 install -e . --break-system-packages
CMD ["python3", "-m", "tools.generic_sif_runner.run"]
