FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless wget curl python3 python3-pip git && \
    rm -rf /var/lib/apt/lists/*
RUN curl -s https://get.nextflow.io | bash && mv nextflow /usr/local/bin/
RUN pip3 install --no-cache-dir nf-core
WORKDIR /data
CMD ["nextflow", "run", "nf-core/rnaseq", "--help"]
