# syntax=docker/dockerfile:1
# ARM64 image for nfcore_nanoseq (nf-core/nanoseq pipeline)
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_nanoseq"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/nanoseq -r 3.1.0 || true
