FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    default-jre \
    perl \
    wget \
    unzip \
    && wget https://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.12.1.zip \
    && unzip fastqc_v0.12.1.zip \
    && chmod +x FastQC/fastqc \
    && mv FastQC /opt/fastqc \
    && ln -s /opt/fastqc/fastqc /usr/local/bin/fastqc \
    && rm fastqc_v0.12.1.zip
CMD ["fastqc", "--version"]
