FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    wget \
    libgomp1 \
    && wget https://github.com/odelaneau/shapeit4/releases/download/v4.2.2/shapeit4.2.2_static \
    && mv shapeit4.2.2_static /usr/local/bin/shapeit4 \
    && chmod +x /usr/local/bin/shapeit4
CMD ["shapeit4", "--version"]
