# syntax=docker/dockerfile:1
# ARM64 image for nfcore_viralrecon
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_viralrecon"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/viralrecon -r 2.6.0 || true
