# syntax=docker/dockerfile:1
# ARM64 image for nfcore_methylseq
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_methylseq"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/methylseq -r 2.6.0 || true
