FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && pip3 install --break-system-packages \
    numpy \
    scipy \
    pysam
COPY rmats.py /usr/local/bin/rmats.py
COPY rMATS /opt/rMATS
RUN chmod +x /usr/local/bin/rmats.py \
    && ln -s /usr/local/bin/rmats.py /usr/local/bin/rmats
CMD ["python3", "/usr/local/bin/rmats.py", "--version"]
