FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    && wget https://s3.amazonaws.com/plink2-assets/alpha6/plink2_linux_aarch64_20250101.zip \
    && unzip plink2_linux_aarch64_20250101.zip \
    && mv plink2 /usr/local/bin/ \
    && rm plink2_linux_aarch64_20250101.zip
CMD ["plink2", "--version"]
