FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    bowtie2 \
    samtools \
    && pip3 install --break-system-packages \
    humann \
    metaphlan
COPY humann /usr/local/bin/humann
RUN chmod +x /usr/local/bin/humann
CMD ["humann", "--version"]
