# syntax=docker/dockerfile:1
# ARM64 image for nfcore_chipseq
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_chipseq"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/chipseq -r 2.0.0 || true
