FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libgomp1 \
    && pip3 install --break-system-packages meeko
COPY vina /usr/local/bin/vina
RUN chmod +x /usr/local/bin/vina
CMD ["vina", "--version"]
