FROM python:3.11-slim-bookworm
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake && rm -rf /var/lib/apt/lists/*
RUN pip install numpy cython --no-cache-dir
RUN pip install macs2 --no-cache-dir --no-binary=:all:

RUN pip install boto3 azure-storage-blob azure-identity --no-cache-dir

COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip install -e . --no-cache-dir

CMD ["python", "-m", "tools.generic_sif_runner.run"]
