FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    wget \
    python3 \
    python3-pip \
    && pip3 install --break-system-packages pymzml pyteomics \
    && wget https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update && apt-get install -y dotnet-runtime-8.0 \
    && rm packages-microsoft-prod.deb
# MaxQuant download: https://www.maxquant.org/
CMD ["dotnet", "--version"]
