FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    default-jre \
    wget \
    unzip \
    && wget https://github.com/broadinstitute/gatk/releases/download/4.5.0.0/gatk-4.5.0.0.zip \
    && unzip gatk-4.5.0.0.zip \
    && mv gatk-4.5.0.0 /opt/gatk \
    && ln -s /opt/gatk/gatk /usr/local/bin/gatk \
    && rm gatk-4.5.0.0.zip
CMD ["gatk", "--version"]
