FROM ubuntu:24.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip libgomp1 wget && rm -rf /var/lib/apt/lists/*
RUN pip3 install --break-system-packages meeko
RUN wget -q https://github.com/ccsb-scripps/AutoDock-Vina/releases/download/v1.2.7/vina_1.2.7_linux_x86_64 \
    -O /usr/local/bin/vina \
    && chmod +x /usr/local/bin/vina
RUN pip3 install boto3 azure-storage-blob azure-identity --break-system-packages --no-cache-dir
COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip3 install -e . --break-system-packages
CMD ["python3", "-m", "tools.generic_sif_runner.run"]
