# syntax=docker/dockerfile:1
# ARM64 image for nfcore_hic
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_hic"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/hic -r 2.1.0 || true
