FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    samtools \
    && pip3 install --break-system-packages \
    velocyto \
    pysam \
    numpy
CMD ["velocyto", "--version"]
