FROM bioconductor/bioconductor_docker:RELEASE_3_18
RUN R -e "BiocManager::install(c('limma','edgeR'))"
RUN pip3 install boto3 azure-storage-blob azure-identity
COPY omnibioai-tool-runtime/tools /app/tools
COPY omnibioai-tool-runtime/omni_tool_runtime /app/omni_tool_runtime
COPY omnibioai-tool-runtime/pyproject.toml /app/pyproject.toml
WORKDIR /app
RUN pip3 install -e . --no-cache-dir
CMD ["python3", "-m", "tools.generic_sif_runner.run"]
