FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    wget \
    && wget https://github.com/COMBINE-lab/salmon/releases/download/v1.10.0/salmon-1.10.0_linux_aarch64.tar.gz \
    && tar -xzf salmon-1.10.0_linux_aarch64.tar.gz \
    && mv salmon-1.10.0_linux_aarch64/bin/salmon /usr/local/bin/ \
    && rm -rf salmon-1.10.0_linux_aarch64*
CMD ["salmon", "--version"]
