FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    wget \
    && wget https://web.stanford.edu/group/pritchardlab/structure_software/release_versions/v2.3.4/structure_kernel_source.tar.gz \
    && tar -xzf structure_kernel_source.tar.gz \
    && cd structure_kernel_src && make && mv structure /usr/local/bin/ \
    && rm -rf structure_kernel_src structure_kernel_source.tar.gz
CMD ["structure", "--help"]
