FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libhdf5-dev \
    && pip3 install --break-system-packages \
    scanpy \
    anndata \
    leidenalg \
    python-igraph \
    scvi-tools \
    matplotlib \
    seaborn
CMD ["python3", "-c", "import scanpy; print('Scanpy', scanpy.__version__)"]
