# syntax=docker/dockerfile:1
# ARM64 image for nfcore_sarek
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_sarek"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/sarek -r 3.4.4 || true
