FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    default-jre \
    wget \
    python3 \
    python3-pip \
    && pip3 install --break-system-packages pyteomics pymzml
# FragPipe download: https://fragpipe.nesvilab.org/
CMD ["java", "-version"]
