FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    perl \
    hmmer \
    python3 \
    libgomp1
COPY RepeatMasker /usr/local/bin/RepeatMasker
RUN chmod +x /usr/local/bin/RepeatMasker
CMD ["RepeatMasker", "--version"]
