# syntax=docker/dockerfile:1
# ARM64 image for nfcore_taxprofiler
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_taxprofiler"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/taxprofiler -r 1.1.8 || true
