# syntax=docker/dockerfile:1
# ARM64 image for nfcore_mag
FROM --platform=linux/arm64 nfcore/base:2.1

LABEL maintainer="OmniBioAI <team@omnibioai.io>"
LABEL tool="nfcore_mag"
LABEL platform="linux/arm64"

RUN nextflow pull nf-core/mag -r 2.3.2 || true
