FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    libgomp1 \
    zlib1g \
    python3
COPY bracken /usr/local/bin/bracken
RUN chmod +x /usr/local/bin/bracken
CMD ["bracken", "--version"]
