FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    wget \
    && wget https://dalexander.github.io/admixture/binaries/admixture_linux-1.3.0.tar.gz \
    && tar -xzf admixture_linux-1.3.0.tar.gz \
    && mv dist/admixture_linux-1.3.0/admixture /usr/local/bin/ \
    && rm -rf admixture_linux-1.3.0.tar.gz dist
CMD ["admixture", "--version"]
