FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    hmmer \
    prodigal \
    && pip3 install --break-system-packages checkm-genome
CMD ["checkm", "--version"]
