FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    python3
COPY pymol_bin /usr/local/bin/pymol
RUN chmod +x /usr/local/bin/pymol
CMD ["pymol", "--version"]
