FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    && pip3 install --break-system-packages \
    numpy \
    pandas \
    scipy \
    bitarray \
    && git clone https://github.com/bulik/ldsc.git /opt/ldsc \
    && ln -s /opt/ldsc/ldsc.py /usr/local/bin/ldsc.py \
    && chmod +x /opt/ldsc/ldsc.py
CMD ["ldsc.py", "--help"]
