FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    bowtie2 \
    samtools \
    && pip3 install --break-system-packages metaphlan
CMD ["metaphlan", "--version"]
